name: Release

on:
  release:
    types: [published]

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
  
  release-zip:
    runs-on: "ubuntu-latest"
    needs: validate
    steps:
      - uses: "actions/checkout@v4"
      - name: Create release zip
        run: |
          cd custom_components/solar_daytopper
          zip -r ../../solar_daytopper.zip .
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./solar_daytopper.zip
          asset_name: solar_daytopper.zip
          asset_content_type: application/zip
